---
# config/config.yaml
#
# please use https://direnv.net/ or similar to manage the environment variables

telegram:
  bot_token: "${TELEGRAM_BOT_TOKEN}" # https://core.telegram.org/bots/tutorial
  chat_id: "${TELEGRAM_CHAT_ID}"
  authorized_users:
    - 19971683

meshtastic:
  connection_type: 'serial'  # 'serial' or 'tcp'
  device: "${MESHTASTIC_DEVICE}" # for serial connection
  default_node_id: '!4e1a832c'
  heartbeat_timeout: 300 # timeout in seconds for node heartbeats
  local_nodes:
    - '!4e1a832c'
    - '!4e19d9a4'
    - '!e72e9724'

logging:
  level: 'info'
  use_syslog: false
  syslog_host: "${SYSLOG_HOST}"
  syslog_port: 514
  syslog_protocol: 'udp'  # 'udp' or 'tcp'
