name: Meshgram

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        check-latest: true
    - name: Install dependencies
      run: |
        python -m pip install -q -U pip
        pip install -q -U -r requirements.txt
        pip install -q -U pytest pytest-asyncio coverage 'prospector[with_everything]'

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage report -m

    - name: Run Prospector
      run: prospector
